// ============================================================
// Buntron CLI - Build Command
// ============================================================

import { resolve, join } from "path";
import { existsSync, mkdirSync, cpSync, readFileSync, writeFileSync } from "fs";

export async function runBuild(args: string[]) {
  const cwd = process.cwd();
  const outDir = resolve(
    cwd,
    args.includes("--outdir") ? args[args.indexOf("--outdir") + 1] : "dist",
  );

  console.log(`\n🔨 Building Buntron app...\n`);

  // Find main file
  let mainFile = "src/main.ts";
  try {
    const pkg = JSON.parse(readFileSync(resolve(cwd, "package.json"), "utf-8"));
    if (pkg.main) mainFile = pkg.main;
  } catch {}

  const mainPath = resolve(cwd, mainFile);
  if (!existsSync(mainPath)) {
    console.error(`Error: Main file not found: ${mainFile}`);
    process.exit(1);
  }

  // Create output directory
  mkdirSync(outDir, { recursive: true });

  console.log(`  Entry: ${mainFile}`);
  console.log(`  Output: ${outDir}`);

  // Build main process with Bun
  console.log("\n  [1/3] Building main process...");

  const buildResult = await Bun.build({
    entrypoints: [mainPath],
    outdir: outDir,
    target: "bun",
    minify: true,
    sourcemap: "external",
  });

  if (!buildResult.success) {
    console.error("  Build failed:");
    for (const log of buildResult.logs) {
      console.error("  ", log);
    }
    process.exit(1);
  }

  console.log("  ✅ Main process built");

  // Copy renderer files
  console.log("  [2/3] Copying renderer files...");

  const rendererDirs = ["src/renderer", "public", "assets"];
  for (const dir of rendererDirs) {
    const srcDir = resolve(cwd, dir);
    if (existsSync(srcDir)) {
      const dstDir = join(outDir, dir);
      cpSync(srcDir, dstDir, { recursive: true });
      console.log(`  ✅ Copied ${dir}/`);
    }
  }

  // Copy preload script if exists
  const preloadCandidates = [
    "src/preload.ts",
    "src/preload.js",
    "preload.ts",
    "preload.js",
  ];
  for (const preload of preloadCandidates) {
    const preloadPath = resolve(cwd, preload);
    if (existsSync(preloadPath)) {
      // Build preload
      const preloadBuild = await Bun.build({
        entrypoints: [preloadPath],
        outdir: outDir,
        target: "browser",
        minify: true,
      });
      if (preloadBuild.success) {
        console.log(`  ✅ Preload script built`);
      }
      break;
    }
  }

  // Generate launcher script
  console.log("  [3/3] Generating launcher...");

  const launcherContent = `#!/usr/bin/env bun
// Auto-generated by buntron build
import "./main.js";
`;
  writeFileSync(join(outDir, "start.ts"), launcherContent);

  // Copy package.json (stripped)
  try {
    const pkg = JSON.parse(readFileSync(resolve(cwd, "package.json"), "utf-8"));
    const distPkg = {
      name: pkg.name,
      version: pkg.version,
      main: "main.js",
      dependencies: pkg.dependencies,
    };
    writeFileSync(
      join(outDir, "package.json"),
      JSON.stringify(distPkg, null, 2),
    );
  } catch {}

  console.log(`
✅ Build complete!
📁 Output: ${outDir}

To run:
  cd ${outDir} && bun start.ts
`);
}
