// ============================================================
// Buntron - EXE Build Script
// ============================================================
// Builds a standalone Buntron app into a single .exe + runtime folder
// Usage: bun run scripts/build-exe.ts
// ============================================================

import { resolve, join, dirname, basename } from "path";
import {
  existsSync,
  mkdirSync,
  cpSync,
  writeFileSync,
  readdirSync,
  readFileSync,
} from "fs";

const buntronRoot = resolve(
  dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1")),
  "..",
);
const outDir = resolve(buntronRoot, "release");
const runtimeDir = join(outDir, "runtime");

console.log(`
╔══════════════════════════════════════════════════╗
║          ⚡ Buntron EXE Builder                   ║
╚══════════════════════════════════════════════════╝
`);

// Step 1: Check prerequisites
console.log("[1/5] Checking prerequisites...");

const hostExe = join(buntronRoot, "native", "build", "BuntronHost.exe");
if (!existsSync(hostExe)) {
  console.error(
    "  ❌ BuntronHost.exe not found. Run: bun run scripts/setup.ts",
  );
  process.exit(1);
}
console.log("  ✅ BuntronHost.exe found");

const buildDir = join(buntronRoot, "native", "build");
const dlls = readdirSync(buildDir).filter((f) => f.endsWith(".dll"));
console.log(`  ✅ ${dlls.length} runtime DLLs found`);

// Step 2: Create the self-contained app source
console.log("\n[2/5] Creating self-contained app source...");

// Build a standalone TS file that embeds the HTML and finds host relative to exe
const appSource = `// Auto-generated by Buntron EXE Builder
import { resolve, join, dirname } from "path";
import { existsSync, mkdirSync } from "fs";

// Find the exe directory at runtime
function getExeDir(): string {
  // When compiled with bun --compile, process.execPath is the exe itself
  return dirname(process.execPath);
}

const exeDir = getExeDir();
const runtimeDir = join(exeDir, "runtime");
const hostExe = join(runtimeDir, "BuntronHost.exe");

if (!existsSync(hostExe)) {
  console.error("ERROR: runtime/BuntronHost.exe not found next to the executable!");
  console.error("Expected at: " + hostExe);
  console.error("Make sure the 'runtime' folder is next to the .exe file.");
  process.exit(1);
}

// HTML content embedded directly
const htmlContent = \`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Buntron Demo App</title>
  <style>
    :root {
      --bg: #0f0f13;
      --bg2: #1a1a24;
      --accent: #7c5cfc;
      --accent2: #9b82fc;
      --glow: rgba(124, 92, 252, 0.25);
      --text: #e8e6f0;
      --text2: #9896a8;
      --border: #2a2a3e;
      --green: #4ceb92;
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', sans-serif;
      background: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    .titlebar {
      height: 32px;
      background: var(--bg2);
      display: flex;
      align-items: center;
      padding: 0 16px;
      border-bottom: 1px solid var(--border);
      -webkit-app-region: drag;
      user-select: none;
    }
    .dot { width: 8px; height: 8px; border-radius: 50%; background: var(--accent); margin-right: 10px; box-shadow: 0 0 8px var(--glow); }
    .titlebar span { font-size: 12px; color: var(--text2); }
    .main {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      text-align: center;
      padding: 40px;
    }
    .icon { font-size: 72px; margin-bottom: 16px; filter: drop-shadow(0 0 20px var(--glow)); }
    h1 {
      font-size: 42px;
      background: linear-gradient(135deg, var(--accent2), var(--accent), #5c4cd6);
      -webkit-background-clip: text;
      -webkit-text-fill-color: transparent;
      margin-bottom: 8px;
    }
    .sub { color: var(--text2); font-size: 16px; margin-bottom: 24px; }
    .badge {
      display: inline-block;
      padding: 6px 18px;
      background: rgba(124,92,252,0.15);
      border: 1px solid rgba(124,92,252,0.3);
      border-radius: 20px;
      font-size: 13px;
      color: var(--accent2);
      font-family: 'Cascadia Code','Fira Code',monospace;
      margin-bottom: 32px;
    }
    .cards {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 14px;
      max-width: 600px;
      width: 100%;
      margin-bottom: 32px;
    }
    .card {
      background: var(--bg2);
      border: 1px solid var(--border);
      border-radius: 12px;
      padding: 20px 16px;
      cursor: pointer;
      transition: all 0.2s;
    }
    .card:hover {
      border-color: var(--accent);
      box-shadow: 0 4px 16px var(--glow);
      transform: translateY(-2px);
    }
    .card-icon { font-size: 28px; margin-bottom: 8px; }
    .card h3 { font-size: 13px; margin-bottom: 4px; }
    .card p { font-size: 11px; color: var(--text2); }
    .console-box {
      width: 100%;
      max-width: 600px;
      background: #0a0a10;
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 16px;
      text-align: left;
      font-family: 'Cascadia Code','Fira Code',monospace;
      font-size: 13px;
      min-height: 80px;
      max-height: 200px;
      overflow-y: auto;
    }
    .log { margin: 2px 0; line-height: 1.6; }
    .log .prefix { color: var(--accent); }
    .log .ok { color: var(--green); }
    .log .ts { color: #6b6980; font-size: 11px; float: right; }
    .footer {
      padding: 16px;
      text-align: center;
      font-size: 11px;
      color: #6b6980;
      border-top: 1px solid var(--border);
    }
    @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; } }
    .anim { animation: fadeIn 0.4s ease forwards; opacity: 0; }
    .anim:nth-child(2) { animation-delay: 0.1s; }
    .anim:nth-child(3) { animation-delay: 0.15s; }
    .anim:nth-child(4) { animation-delay: 0.2s; }
  </style>
</head>
<body>
  <div class="titlebar">
    <div class="dot"></div>
    <span>Buntron Demo</span>
  </div>
  <div class="main">
    <div class="icon anim">⚡</div>
    <h1 class="anim">Buntron</h1>
    <p class="sub anim">Desktop framework powered by Bun + WebView2</p>
    <div class="badge anim">standalone .exe build</div>
    <div class="cards anim">
      <div class="card" onclick="doAction('counter')">
        <div class="card-icon">🔢</div>
        <h3>Counter</h3>
        <p>Click to count</p>
      </div>
      <div class="card" onclick="doAction('time')">
        <div class="card-icon">⏰</div>
        <h3>Time</h3>
        <p>Current time</p>
      </div>
      <div class="card" onclick="doAction('random')">
        <div class="card-icon">🎲</div>
        <h3>Random</h3>
        <p>Random number</p>
      </div>
    </div>
    <div class="console-box" id="console"></div>
  </div>
  <div class="footer">Built with Buntron — Bun + WebView2 + Win32</div>
  <script>
    const con = document.getElementById('console');
    let counter = 0;
    function log(msg, cls) {
      const d = document.createElement('div');
      d.className = 'log';
      const t = new Date().toLocaleTimeString('en-GB',{hour12:false});
      d.innerHTML = '<span class="prefix">❯</span> <span class="'+(cls||'')+'">' + msg + '</span><span class="ts">' + t + '</span>';
      con.appendChild(d);
      con.scrollTop = con.scrollHeight;
    }
    log('Buntron EXE app started!', 'ok');
    log('WebView2 rendering active', 'ok');

    function doAction(type) {
      if (type === 'counter') { counter++; log('Counter: ' + counter); }
      else if (type === 'time') { log('Time: ' + new Date().toLocaleString()); }
      else if (type === 'random') { log('Random: ' + Math.floor(Math.random() * 1000000)); }
    }
  </script>
</body>
</html>\`;

// Start HTTP server for content
const server = Bun.serve({
  port: 0,
  fetch(req) {
    return new Response(htmlContent, {
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  },
});

const url = "http://localhost:" + server.port + "/";
console.log("[Buntron] Content server: " + url);

// User data directory
const userDataDir = join(
  process.env.LOCALAPPDATA || process.env.APPDATA || exeDir,
  "BuntronDemo",
  "WebView2Data"
);
mkdirSync(userDataDir, { recursive: true });

// Spawn host process
const hostProc = Bun.spawn([hostExe, userDataDir], {
  stdin: "pipe",
  stdout: "pipe",
  stderr: "pipe",
});

console.log("[Buntron] Host PID: " + hostProc.pid);

const decoder = new TextDecoder();
let buf = "";
let reqId = 1;

function send(cmd: string, params: any = {}): number {
  const id = reqId++;
  const msg = JSON.stringify({ cmd, id, params }) + "\\n";
  hostProc.stdin.write(msg);
  return id;
}

function handle(msg: any) {
  if (msg.event === "ready") {
    console.log("[Buntron] Host ready, creating window...");
    send("createWindow", {
      width: 750,
      height: 580,
      title: "Buntron Demo \\u26A1",
      center: true,
      backgroundColor: "#0f0f13",
      url: url,
      devTools: false,
    });
  }
  if (msg.event === "reply" && msg.windowId) {
    console.log("[Buntron] Window created (ID: " + msg.windowId + ")");
  }
  if (msg.event === "windowClosed" || msg.event === "allWindowsClosed") {
    console.log("[Buntron] Window closed. Exiting.");
    send("quit");
    setTimeout(() => { server.stop(); process.exit(0); }, 300);
  }
}

// Read stdout
(async () => {
  const reader = hostProc.stdout.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      let idx;
      while ((idx = buf.indexOf("\\n")) >= 0) {
        const line = buf.substring(0, idx).trim();
        buf = buf.substring(idx + 1);
        if (line) { try { handle(JSON.parse(line)); } catch {} }
      }
    }
  } catch {}
  server.stop();
  process.exit(0);
})();

// Read stderr silently
(async () => {
  const reader = hostProc.stderr.getReader();
  try { while (true) { const { done } = await reader.read(); if (done) break; } } catch {}
})();

process.on("SIGINT", () => { send("quit"); setTimeout(() => process.exit(0), 500); });
`;

const appSrcPath = join(outDir, "_app_src.ts");
mkdirSync(outDir, { recursive: true });
writeFileSync(appSrcPath, appSource, "utf-8");
console.log("  ✅ App source generated");

// Step 3: Copy runtime files
console.log("\n[3/5] Copying runtime files...");
mkdirSync(runtimeDir, { recursive: true });

// Copy BuntronHost.exe
cpSync(hostExe, join(runtimeDir, "BuntronHost.exe"));
console.log("  ✅ BuntronHost.exe");

// Copy all DLLs from build dir
for (const dll of dlls) {
  cpSync(join(buildDir, dll), join(runtimeDir, dll));
  console.log(`  ✅ ${dll}`);
}

// Step 4: Compile to standalone EXE with bun --compile
console.log("\n[4/5] Compiling standalone EXE...");

const exeName = "BuntronDemo.exe";
const exePath = join(outDir, exeName);

const compileProc = Bun.spawnSync(
  [
    "bun",
    "build",
    "--compile",
    "--minify",
    "--target=bun-windows-x64",
    appSrcPath,
    "--outfile",
    exePath,
  ],
  {
    cwd: outDir,
    env: { ...process.env },
  },
);

if (compileProc.exitCode !== 0) {
  console.error("  ❌ Compilation failed:");
  console.error(compileProc.stderr.toString());
  console.error(compileProc.stdout.toString());
  process.exit(1);
}

console.log(`  ✅ ${exeName} compiled`);

// Step 5: Cleanup temp source
try {
  require("fs").unlinkSync(appSrcPath);
} catch {}

// Get file sizes
const { statSync } = require("fs");
const exeSize = (statSync(exePath).size / 1024 / 1024).toFixed(1);
let runtimeSize = 0;
for (const f of readdirSync(runtimeDir)) {
  runtimeSize += statSync(join(runtimeDir, f)).size;
}
const runtimeSizeMB = (runtimeSize / 1024 / 1024).toFixed(1);

console.log(`
╔══════════════════════════════════════════════════╗
║          ✅ EXE Build Complete!                   ║
╚══════════════════════════════════════════════════╝

📁 Output: ${outDir}

  ${exeName}           ${exeSize} MB (Bun runtime + app)
  runtime/              ${runtimeSizeMB} MB (WebView2 host + DLLs)

Total: ${(parseFloat(exeSize) + parseFloat(runtimeSizeMB)).toFixed(1)} MB

To run:
  cd release
  .\\${exeName}

To distribute:
  ZIP the entire 'release' folder.
  Requires WebView2 Runtime (included in Windows 10/11).
`);
